{
  "singleton_construct_error": "Une instance de la classe de singleton %(classname)s ne peut pas être construite",
  "create_local_item_error": "Erreur dans createLocalItem : ",
  "error_filtering_remote_items": "Erreur lors du filtrage de la liste des éléments éloignés dans listModifiedRemoteItemNames",
  "push_error_creating_item": "Erreur d'insertion lors de la création de l'élément : ",
  "push_error_updating_item": "Erreur d'insertion lors de la mise à jour de l'élément : ",
  "pushed_item_error": "Erreur d'élément inséré : ",
  "pushed_item_retry": "Nouvelle tentative d'insertion de l'élément '%(name)s'. Erreur : %(message)s",
  "invalid_path": "Chemin non valide : %(path)s",
  "timed_out_closing_read_stream": "Expiration du délai d'attente de fermeture du flux de lecture",
  "remote_asset_not_found": "Actif éloigné introuvable : ",
  "cannot_push_item": "L'élément '%(name)s' n'a pas pu être inséré.",
  "cannot_pull_item": "L'élément '%(name)s' n'a pas pu être extrait.",

  "deleted_original_file": "Fichier d'origine supprimé : %(old_name)s ; nouveau fichier : %(new_name)s",
  "error_cancelling_job": "Erreur lors de l'annulation du travail : id %(id)s",
  "error_fs_get_item": "Erreur dans le fichier système getItem",
  "error_fs_get_filestats": "Erreur dans la fonction getFileStats du système de fichiers pour %(name)s.",
  "error_parsing_item": "Erreur lors de l'analyse syntaxique de l'élément pour le fichier %(name)s. %(message)s",
  "get_items_error": "Erreur lors de l'obtention des éléments %(service_name)s : ",
  "save_item_write_failed": "saveItem n'est pas parvenu à écrire dans le fichier %(path)s",
  "save_item_write_failed_bad_path": "saveItem n'est pas parvenu à écrire dans le fichier %(path)s ; chemin d'accès incorrect",
  "close_stream_failed": "CloseStream a échoué avec l'erreur : ",
  "error_options_file": "Erreur lors de la lecture du fichier d'options de configuration : %(filename)s. %(error)s",

  "name_required": "Vous devez spécifier un nom.",
  "category_exists": "Il existe déjà une catégorie nommée %(name)s.",
  "template_required": "Le modèle doit être spécifié.",
  "cannot_get_asset": "Impossible d'obtenir l'actif : %(path)s ; code de statut : %(code)s",
  "deleted_asset": "L'actif dont l'ID est %(id)s a été supprimé",
  "create_asset_metadata_error": "Erreur lors de la création des métadonnées d'actif : ",
  "deleted_item": "L'élément dont l'ID est %(id)s a été supprimé",
  "deleted_item_retry": "Nouvelle tentative de suppression de l'élément '%(name)s'. Erreur : %(message)s",
  "get_item_error": "Erreur lors de l'obtention de l'élément %(service_name)s : ",
  "create_item_error": "Erreur lors de la création de l'élément %(service_name)s : ",
  "update_item_error": "Erreur lors de la mise à jour de l'élément %(service_name)s : ",
  "delete_item_error": "Erreur lors de la suppression de l'élément %(service_name)s : ",
  "delete_rendition_error": "La suppression des rendus n'est pas prise en charge. ID : %(id)s, options : %(opts)s",
  "error_tenant_map": "Erreur dans loadTenantMap : ",
  "error_save_hashes": "Erreur dans saveHashes : ",
  "error_update_hashes": "Erreur dans updateHashes : ",
  "error_remove_hashes": "Erreur dans removeHashes : ",
  "error_remove_all_hashes": "Erreur dans removeAllHashes : ",
  "error_set_last_pull_timestamp": "Erreur dans setLastPullTimestamp : ",
  "error_set_last_push_timestamp": "Erreur dans setLastPushTimestamp : ",
  "error_get_hashes_for_file": "Erreur dans getHashesForFile : ",

  "error_unsupported_endpoint": "L'API %(service_name)s ne prend pas en charge le noeud final %(endpoint)s.",
  "unknown_error": "Erreur inconnue",
  "service_unavailable": "Un service IBM Watson Content Hub n'est actuellement pas disponible.  ",
  "service_error": "Un service IBM Watson Content Hub signale des difficultés techniques.  ",
  "service_response_error": "Un service IBM Watson Content Hub a renvoyé le code d'erreur %(code)d et le message de statut : %(message)s",
  "operation_failed": "Echec de l'opération avec l'erreur suivante : ",
  "async_parallel_limit_error": "L'appel parallelLimit asynchrone a échoué avec l'erreur suivante : ",
  "async_parallel_limit_results": "Résultats de l'appel parallelLimit asynchrone : ",
  "please_try": "Essayez à nouveau ultérieurement.  Si le problème persiste, contactez le service clients et incluez les informations de journal disponibles dans %(log_dir)s",
  "conflict":"Le service a rencontré et renvoyé une condition d'erreur lors du traitement de la demande pour cet artefact.",
  "login_missing_authn":"Le service de connexion n'a pas réussi à répondre avec des informations d'authentification valides.",
  "digest_mismatch": "Le prétraitement %(cli_digest)s de l'actif %(asset)s extrait ne correspond pas au prétraitement du serveur %(server_digest)s.",
  "retry_failed_request": "Une demande (%(id)d) ayant échoué sera renouvelée. %(message)s",
  "retry_failed_retry": "Une demande (%(id)d) renouvelée (tentative %(attempt)d) a échoué avant que le nombre maximal de tentatives n'ait été atteint. %(message)s",
  "retry_next_attempt": "Une demande (%(id)d) sera renouvelée (tentative %(attempt)d) dans %(delay)d millisecondes.",
  "retry_success": "Une demande (%(id)d) renouvelée a abouti après %(attempt)d tentatives.",
  "retry_max_attempts": "Une demande (%(id)d) a été renouvelée autant de fois que possible."
}

