{
  "singleton_construct_error": "Uma instância de classe singleton % (classname)s não pode ser construída",
  "create_local_item_error": "Erro em createLocalItem:",
  "error_filtering_remote_items": "Erro ao filtrar lista de itens remotos em listModifiedRemoteItemNames",
  "push_error_creating_item": "Erro de push ao criar o item: ",
  "push_error_updating_item": "Erro de push ao atualizar o item: ",
  "pushed_item_error": "Erro de envio de item por push: ",
  "invalid_path": "Caminho inválido % (path)s",
  "timed_out_closing_read_stream": "Ocorreu um tempo limite esperando fechamento de fluxo de leitura",
  "remote_asset_not_found": "Ativo remoto não localizado: ",

  "deleted_original_file": "Excluído arquivo original: %(old_name)s novo arquivo: %(new_name)s",
  "error_cancelling_job": "Erro ao cancelar tarefa: ID %(id)s",
  "error_fs_get_item": "Erro no sistema de arquivos getItem",
  "error_parsing_item": "Erro ao analisar item para o arquivo: %(name)s. %(message)s\n%(body)s",
  "get_items_error": "Erro ao obter itens %(service_name)s:",
  "save_item_write_failed": "saveItem falhou ao gravar no arquivo %(path)s",
  "save_item_write_failed_bad_path": "saveItem falhou ao gravar no arquivo %(path)s caminho ruim",
  "close_stream_failed": "closeStream falhou com o erro: ",

  "name_required": "O nome deve ser especificado.",
  "category_exists": "Uma categoria com o nome %(name)s já existe.",
  "template_required": "O modelo deve ser especificado.",
  "presentation_exists": "Uma apresentação com o nome %(name)s já existe.",
  "cannot_get_asset": "Não é possível obter ativo: %(path)s; código de status: %(code)s",
  "deleted_asset": "Ativo excluído com ID: %(id)s",
  "get_item_error": "Erro ao obter item %(service_name)s:",
  "create_item_error": "Erro ao criar item %(service_name)s:",
  "update_item_error": "Erro ao atualizar item %(service_name)s:",
  "delete_item_error": "Erro ao excluir item %(service_name)s:",
  "error_tenant_map": "Erro em loadTenantMap: ",
  "error_save_hashes": "Erro em saveHashes: ",
  "error_update_hashes": "Erro em updateHashes: ",
  "error_set_last_pull_timestamp": "Erro em setLastPullTimestamp: ",
  "error_set_last_push_timestamp": "Erro em setLastPushTimestamp: ",
  "error_get_hashes_for_file": "Erro em getHashesForFile: ",

  "unknown_error": "Erros Desconhecido",
  "service_unavailable": "Um serviço IBM Watson Content Hub atualmente está indisponível.",
  "service_error": "Um serviço IBM Watson Content Hub está relatando dificuldades técnicas.",
  "service_response_error": "Um serviço IBM Watson Content Hub retornou o código de erro %(code)d e mensagem de status: %(message)s",
  "operation_failed": "A operação falhou com o erro: ",
  "async_parallel_limit_error": "A chamada assíncrona parallelLimit falhou com o erro: ",
  "async_parallel_limit_results": "Resultados do parallelLimit assíncrono: ",
  "please_try": "Tente novamente posteriormente.  Se o problema persistir, entre em contato com o suporte ao cliente e inclua as informações de log disponíveis em %(log_dir)s",
  "conflict":"O serviço encontrou e retornou uma condição de erro ao processar a solicitação para esse artefato."

}

